function B = B_fun(a1,l1,l2,m1,m2,q2)
%B_FUN
%    B = B_FUN(A1,L1,L2,M1,M2,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    12-May-2020 22:53:29

B = reshape([l1.^2.*m1.*(4.0./3.0)+(l2.^2.*m2)./3.0+m2.*(a1.^2+l2.^2+a1.*l2.*cos(q2).*2.0),(l2.^2.*m2)./3.0+l2.*m2.*(l2+a1.*cos(q2)),(l2.^2.*m2)./3.0+l2.*m2.*(l2+a1.*cos(q2)),l2.^2.*m2.*(4.0./3.0)],[2,2]);
