function G = G_fun(a1,g0,l1,l2,m1,m2,q1,q2)
%G_FUN
%    G = G_FUN(A1,G0,L1,L2,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    13-May-2020 11:44:24

G = [g0.*m2.*(l2.*cos(q1+q2)+a1.*cos(q1))+g0.*l1.*m1.*cos(q1);g0.*l2.*m2.*cos(q1+q2)];
